<?php

namespace Database\Seeders;

use App\Models\AiSession;
use App\Models\Connector;
use App\Models\Organization;
use App\Models\User;
use App\Models\Workflow;
use App\Models\WorkflowRun;
use App\Models\WorkflowVersion;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        $organization = Organization::create([
            'name' => 'Orbit Labs',
            'slug' => 'orbit-labs',
            'plan' => 'founder',
        ]);

        $user = User::factory()->create([
            'organization_id' => $organization->id,
            'name' => 'Builder Jane',
            'email' => 'jane@example.com',
            'password' => Hash::make('password'),
        ]);

        Connector::insert([
            [
                'slug' => 'http-trigger',
                'name' => 'HTTP Trigger',
                'category' => 'triggers',
                'schema' => json_encode([
                    'fields' => [
                        ['key' => 'method', 'type' => 'string', 'options' => ['GET', 'POST']],
                        ['key' => 'path', 'type' => 'string'],
                    ],
                ]),
                'supports_ai_tooling' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'ai-transform',
                'name' => 'AI Transform',
                'category' => 'ai',
                'schema' => json_encode([
                    'fields' => [
                        ['key' => 'model', 'type' => 'string'],
                        ['key' => 'prompt', 'type' => 'text'],
                    ],
                ]),
                'supports_ai_tooling' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'slack-send',
                'name' => 'Slack Send',
                'category' => 'actions',
                'schema' => json_encode([
                    'fields' => [
                        ['key' => 'channel', 'type' => 'string'],
                        ['key' => 'message', 'type' => 'text'],
                    ],
                ]),
                'supports_ai_tooling' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        $workflow = Workflow::create([
            'organization_id' => $organization->id,
            'user_id' => $user->id,
            'name' => 'Summarize leads and post to Slack',
            'description' => 'Generated by the AI seeder',
            'status' => 'active',
            'metadata' => ['source' => 'seed'],
        ]);

        $graph = [
            'nodes' => [
                ['id' => 'http_trigger', 'type' => 'http-trigger', 'data' => ['method' => 'POST', 'path' => '/leads']],
                ['id' => 'ai_transform', 'type' => 'ai-transform', 'data' => ['model' => 'gpt-4o', 'prompt' => 'Summarize the lead']],
                ['id' => 'slack_send', 'type' => 'slack-send', 'data' => ['channel' => '#leads', 'message' => '']],
            ],
            'edges' => [
                ['id' => 'edge-1', 'source' => 'http_trigger', 'target' => 'ai_transform'],
                ['id' => 'edge-2', 'source' => 'ai_transform', 'target' => 'slack_send'],
            ],
        ];

        $version = WorkflowVersion::create([
            'workflow_id' => $workflow->id,
            'version' => 1,
            'graph' => $graph,
            'ai_prompt' => 'Summarize inbound leads and notify Slack',
            'created_by' => $user->id,
        ]);

        WorkflowRun::create([
            'workflow_id' => $workflow->id,
            'workflow_version_id' => $version->id,
            'status' => 'success',
            'graph_snapshot' => $graph,
            'node_results' => [
                [
                    'node_id' => 'http_trigger',
                    'status' => 'success',
                    'output' => ['lead' => ['name' => 'Ada', 'company' => 'Tetra']],
                ],
                [
                    'node_id' => 'ai_transform',
                    'status' => 'success',
                    'output' => ['summary' => 'Ada from Tetra wants a pricing chat.'],
                ],
                [
                    'node_id' => 'slack_send',
                    'status' => 'success',
                    'output' => ['message' => 'Posted to #leads'],
                ],
            ],
            'started_at' => now()->subMinutes(5),
            'finished_at' => now()->subMinutes(4),
        ]);

        AiSession::create([
            'workflow_id' => $workflow->id,
            'user_id' => $user->id,
            'prompt' => 'Summarize inbound leads and post to Slack',
            'response' => [
                'summary' => 'Workflow created with HTTP trigger -> AI -> Slack',
                'draft_version' => $version->version,
            ],
            'token_cost' => 0.12,
        ]);
    }
}
